# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/george/Documents/local_projects/dryrun/dryrun.srcs/sources_1/bd/ugv/ip/ugv_axi_uartlite_0_1/ugv_axi_uartlite_0_1.xci
# IP: The module: 'ugv_axi_uartlite_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/george/Documents/local_projects/dryrun/dryrun.srcs/sources_1/bd/ugv/ip/ugv_axi_uartlite_0_1/ugv_axi_uartlite_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ugv_axi_uartlite_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/george/Documents/local_projects/dryrun/dryrun.srcs/sources_1/bd/ugv/ip/ugv_axi_uartlite_0_1/ugv_axi_uartlite_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ugv_axi_uartlite_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/george/Documents/local_projects/dryrun/dryrun.srcs/sources_1/bd/ugv/ip/ugv_axi_uartlite_0_1/ugv_axi_uartlite_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ugv_axi_uartlite_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/george/Documents/local_projects/dryrun/dryrun.srcs/sources_1/bd/ugv/ip/ugv_axi_uartlite_0_1/ugv_axi_uartlite_0_1.xci
# IP: The module: 'ugv_axi_uartlite_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/george/Documents/local_projects/dryrun/dryrun.srcs/sources_1/bd/ugv/ip/ugv_axi_uartlite_0_1/ugv_axi_uartlite_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ugv_axi_uartlite_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/george/Documents/local_projects/dryrun/dryrun.srcs/sources_1/bd/ugv/ip/ugv_axi_uartlite_0_1/ugv_axi_uartlite_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ugv_axi_uartlite_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/george/Documents/local_projects/dryrun/dryrun.srcs/sources_1/bd/ugv/ip/ugv_axi_uartlite_0_1/ugv_axi_uartlite_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ugv_axi_uartlite_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
