# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/NGCP_Embedded_SDK/ugv.xdc

# Block Designs: bd/ugv/ugv.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv || ORIG_REF_NAME==ugv} -quiet] -quiet

# IP: bd/ugv/ip/ugv_processing_system7_0_0/ugv_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_processing_system7_0_0 || ORIG_REF_NAME==ugv_processing_system7_0_0} -quiet] -quiet

# IP: bd/ugv/ip/ugv_motorPWM_0_0/ugv_motorPWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_motorPWM_0_0 || ORIG_REF_NAME==ugv_motorPWM_0_0} -quiet] -quiet

# IP: bd/ugv/ip/ugv_motorPWM_0_1/ugv_motorPWM_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_motorPWM_0_1 || ORIG_REF_NAME==ugv_motorPWM_0_1} -quiet] -quiet

# IP: bd/ugv/ip/ugv_motorPWM_0_2/ugv_motorPWM_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_motorPWM_0_2 || ORIG_REF_NAME==ugv_motorPWM_0_2} -quiet] -quiet

# IP: bd/ugv/ip/ugv_xlslice_0_0/ugv_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_xlslice_0_0 || ORIG_REF_NAME==ugv_xlslice_0_0} -quiet] -quiet

# IP: bd/ugv/ip/ugv_xlslice_0_1/ugv_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_xlslice_0_1 || ORIG_REF_NAME==ugv_xlslice_0_1} -quiet] -quiet

# IP: bd/ugv/ip/ugv_xbar_0/ugv_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_xbar_0 || ORIG_REF_NAME==ugv_xbar_0} -quiet] -quiet

# IP: bd/ugv/ip/ugv_ps7_0_axi_periph_0/ugv_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_ps7_0_axi_periph_0 || ORIG_REF_NAME==ugv_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ugv/ip/ugv_rst_ps7_0_100M_0/ugv_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_rst_ps7_0_100M_0 || ORIG_REF_NAME==ugv_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ugv/ip/ugv_motorEncoder_0_0/ugv_motorEncoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_motorEncoder_0_0 || ORIG_REF_NAME==ugv_motorEncoder_0_0} -quiet] -quiet

# IP: bd/ugv/ip/ugv_motorEncoder_0_1/ugv_motorEncoder_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_motorEncoder_0_1 || ORIG_REF_NAME==ugv_motorEncoder_0_1} -quiet] -quiet

# IP: bd/ugv/ip/ugv_motorEncoder_1_0/ugv_motorEncoder_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_motorEncoder_1_0 || ORIG_REF_NAME==ugv_motorEncoder_1_0} -quiet] -quiet

# IP: bd/ugv/ip/ugv_xlconcat_0_0/ugv_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_xlconcat_0_0 || ORIG_REF_NAME==ugv_xlconcat_0_0} -quiet] -quiet

# IP: bd/ugv/ip/ugv_axi_uartlite_0_0/ugv_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_axi_uartlite_0_0 || ORIG_REF_NAME==ugv_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/ugv/ip/ugv_axi_uartlite_0_1/ugv_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_axi_uartlite_0_1 || ORIG_REF_NAME==ugv_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/ugv/ip/ugv_axi_uartlite_0_2/ugv_axi_uartlite_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_axi_uartlite_0_2 || ORIG_REF_NAME==ugv_axi_uartlite_0_2} -quiet] -quiet

# IP: bd/ugv/ip/ugv_servoz3_0_0/ugv_servoz3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_servoz3_0_0 || ORIG_REF_NAME==ugv_servoz3_0_0} -quiet] -quiet

# IP: bd/ugv/ip/ugv_xadc_wiz_0_0/ugv_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_xadc_wiz_0_0 || ORIG_REF_NAME==ugv_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/ugv/ip/ugv_PmodGPS_0_0/ugv_PmodGPS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_PmodGPS_0_0 || ORIG_REF_NAME==ugv_PmodGPS_0_0} -quiet] -quiet

# IP: bd/ugv/ip/ugv_auto_pc_0/ugv_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ugv_auto_pc_0 || ORIG_REF_NAME==ugv_auto_pc_0} -quiet] -quiet

# XDC: bd/ugv/ugv_ooc.xdc
